Подсоединение по адресу localhost:5432 отклонено. Проверьте что хост …
Bib8/school pull request #3
Opened 2022-05-07 08:11 UTC by Bib8

…и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.

2022-05-07 11:54 UTC, OlgaLugacheva requested changes

2022-05-07 11:54 UTC, OlgaLugacheva commented on scripts.sql
> +select * from
этого запроса явно недостаточно

2022-05-07 11:54 UTC, OlgaLugacheva commented on src/main/java/repository/StudentRepository.java
> +    Collection<Student> findAllByNameOrderByNameContainsIgnoreCase();
судя по названию метода у него должен быть параметр name  , часть orderByName должна быть в конце

2022-05-07 11:54 UTC, OlgaLugacheva commented on src/main/java/repository/StudentRepository.java
> +    Collection<Student> findAllByAgeOrderByAge();
судя по названию метода у него должен быть параметр age

2022-05-13 08:31 UTC, closed without merging

2022-05-13 08:31 UTC, Bib8 commented
add res